packages:
  - apps/*
  - packages/*
  - packages/ui/*

catalog:
  "@biomejs/biome": 2.3.7
  "@date-fns/tz": 1.4.1
  "@pandacss/dev": 1.4.3
  "@pandacss/preset-panda": 1.4.3
  "@tsconfig/strictest": ^2.0.5
  date-fns: 4.1.0
  motion: 12.23.24
  typescript: 5.9.3
  ultracite: 6.3.6

catalogs:
  react19:
    "@types/react": ^19.2.7
    "@types/react-dom": ^19.2.3
    react: ^19.2.3
    react-dom: ^19.2.3

onlyBuiltDependencies:
  - "@biomejs/biome"
  - contentlayer2
  - esbuild
  - protobufjs
  - sharp
