packages:
  - "apps/*"
  - "packages/*"
  - "packages/ui/*"

catalog:
  typescript: ^5.8.2
  date-fns: ^4.1.0
  "@date-fns/tz": ^1.2.0
  motion: ^12.5.0
  "@biomejs/biome": ^1.9.4
  "@pandacss/dev": ^0.53.2
  "@tsconfig/strictest": ^2.0.5
  "@pandacss/preset-panda": ^0.53.2
