packages:
  - apps/*
  - packages/*
  - packages/ui/*

catalog:
  "@biomejs/biome": 2.2.6
  "@date-fns/tz": ^1.2.0
  "@pandacss/dev": 1.4.3
  "@pandacss/preset-panda": 1.4.3
  "@tsconfig/strictest": ^2.0.5
  date-fns: ^4.1.0
  motion: ^12.23.24
  typescript: 5.9.3

onlyBuiltDependencies:
  - "@biomejs/biome"
  - contentlayer2
  - esbuild
  - protobufjs
  - sharp
