import type { NextPage } from 'next'
import Wow from '@/components/Wow'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wow>Wow</Wow>
    </div>
  )
}

export default Home
